{% set name = "poincare" %}
{% set version = "0.6.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/poincare-{{ version }}.tar.gz
  sha256: d50f092d3083fc6423afc6dda0045def7ac8440a3640532267ecdd5b5cc95f8a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - pint
    - pint-pandas
    - scipy
    - symbolite >=0.6.0
    - tabulate
    - typing_extensions
    - scipy-events

test:
  imports:
    - poincare
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/maurosilber/poincare
  summary: Simulation of dynamical systems.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maurosilber
    - hgrecco
