{% set name = "poincare" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/poincare-{{ version }}.tar.gz
  sha256: 95476ec9e9f88946c97a5e7bdbd4e7535038c597ef2924c2c36f7e4a8e0d2040

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.7
    - numpy
    - pandas
    - pint
    - pint-pandas
    - scipy
    - symbolite >=0.4
    - tabulate
    - typing-extensions

test:
  imports:
    - poincare
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/maurosilber/poincare
  summary: Simulation of dynamical systems.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maurosilber
    - hgrecco
